# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_APIS/03c_util_extras.ipynb.

# %% auto 0
__all__ = ['linear_kernel', 'polynomial_kernel', 'rbf_kernel']

# %% ../../nbs/01_APIS/03c_util_extras.ipynb 3
from fastcore.utils import *
import numpy as np
import pandas as pd
import gc
import numba



# %% ../../nbs/01_APIS/03c_util_extras.ipynb 5
def linear_kernel(**kwargs):
    def f(x1, x2):
        return np.inner(x1, x2)
    return f


def polynomial_kernel(power, coef, **kwargs):
    def f(x1, x2):
        return (np.inner(x1, x2) + coef)**power
    return f


def rbf_kernel(gamma, **kwargs):
    def f(x1, x2):
        distance = np.linalg.norm(x1 - x2) ** 2
        return np.exp(-gamma * distance)
    return f
